### ISSUE TITLE
Don't works with the current v3 api

### ISSUE THREAD

**Issue by elcreator** [viniciusbo/zabbix-emqtt#3] opened 2020-06-21 03:31 UTC
Hello, I'm trying to fix this to work with current API v3. https://github.com/elcreator/zabbix-emqtt/blob/master/externalscripts/emqtt.sh

Currently it correctly parses the values from the first (and single one for me) node in the cluster.

Problem that I have is when I launch this even manually from the command line 

$ zabbix_sender -z 127.0.0.1 -s 127.0.0.1 -k 'emqtt[messages/retained]' -o 3
Response from "127.0.0.1:10051": "processed: 0; failed: 1; total: 1; seconds spent: 0.000018"
sent: 1; skipped: 0; total: 1

it don't works. Trappers was configured and exists, host is reachable and allowed.

**Comment by viniciusbo** [comment] 2020-06-21 19:52
It's probably because you didn't update the template in order to accept the new keys.

Since it's not a bug in zabbix-emqtt itself, I'm closing this issue.

**Closed as completed by viniciusbo** 2020-06-21 19:52 UTC

**Comment by elcreator** [comment] 2020-06-21 20:08
I have imported template as described.

![52 items was successfully imported](https://i.imgur.com/uzSZSSI.png)

zabbix-emqtt don't works at all as the current API version is 4 and minimal is 3 according to 
 https://www.emqx.io/downloads/enterprise/ .
Version 2 exists only for non-enterprise version.

**Comment by viniciusbo** [comment] 2020-06-21 23:35
I mean you need to update this file adding the new fields https://github.com/elcreator/zabbix-emqtt/blob/master/zbx_emqtt_template.xml which seems you didn't.

**Comment by elcreator** [comment] 2020-06-22 00:03
no, provided example 

zabbix_sender -z 127.0.0.1 -s 127.0.0.1 -k 'emqtt[messages/retained]' -o 3
Response from "127.0.0.1:10051": "processed: 0; failed: 1; total: 1; seconds spent: 0.000018"
sent: 1; skipped: 0; total: 1

tests only messages/retained field that exists in original template unchanged

https://github.com/elcreator/zabbix-emqtt/blob/master/zbx_emqtt_template.xml#L634

That's why I have not changed any other fields and have not created pull request.

**Comment by viniciusbo** [comment] 2020-06-22 00:05
That's what I'm saying, **you have to update the template file if you change the original keys**.

**Comment by elcreator** [comment] 2020-07-01 20:55
Please recheck example provided by me in this comment.
I have executed in console (not in the script as it's for debug only!)

zabbix_sender -z 127.0.0.1 -s 127.0.0.1 -k 'emqtt[messages/retained]' -o 3

You already have emqtt[messages/retained] in the template file.
So I don't need to update the template file to make this single line working.
But it not works.

**Comment by viniciusbo** [comment] 2020-07-02 14:01
@elcreator I'm sorry but I can't help you with this, since this plugin is intended to be used with API v2. Most probably the JSON response structure changed, and you will have to update the processing done by jq to fetch the new value.

I'd suggest running `emqtt.sh` script manually and see what's being returned, then update the `out` lines to match the new JSON structure.
